Update MvcUriComponentsBuilder.java
Method with following signature "public static UriComponentsBuilder fromMethodName(Class<?> controllerType,String methodName, Object... argumentValues)" makes use of the getParameterCount() method found in the java.lang.reflect.Method class. This is specific to Java 8 and will cause projects using prior versions of Java to throw an exception (java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameterCount()). My proposed modification is to change it to getParameterTypes().length to get the total number of parameters.