add setTransactionManagerBeanName
add setTransactionManagerBeanName for set TransactionAspectSupport#setTransactionManagerBeanName

so one beanfactory can have more than one TransactionManager 
otherwise will:
`
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.transaction.PlatformTransactionManager] is defined: expected single matching bean but found 2: transactionManagerLog,transactionManager
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:368)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371)
`