Fail early FactoryBean instantiation for LinkageError
In 0288878 to resolve gh-22409, a little bug was introduced:
if there is LinkageError in FactoryBean instantiation, no first exception.

In JVM, if a class cannot be initialized, it acts like this:
- at the first time, it will show the real reason and stack
- then, only show "NoClassDefFoundError: Could not initialize class xxx"