Introduce CorsUtils#isSameOrigin()
This commit modifies DefaultCorsProcessor to use a new
CorsUtils#isSameOrigin() method instead of WebUtils#isSameOrigin()
in order to avoid NoClassDefFoundError with non Servlet-based
engines.

Issue: SPR-14545