Fixed a test failure caused by conflicting versions of slf4j.
Testsuite: org.springframework.orm.hibernate3.HibernateJtaTransactionTests
    [junit] Tests run: 36, Failures: 0, Errors: 8, Time elapsed: 0.147 sec
    [junit]
    [junit] ------------- Standard Error -----------------
    [junit] SLF4J: slf4j-api 1.6.x (or later) is incompatible with this binding.
    [junit] SLF4J: Your binding is version 1.5.5 or earlier.
    [junit] SLF4J: Upgrade your binding to version 1.6.x. or 2.0.x
    [junit] ------------- ---------------- ---------------
    [junit] Testcase: testJtaTransactionCommitWithPreBound(org.springframework.orm.hibernate3.HibernateJtaTransactionTests):	Caused an ERROR
    [junit] org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
    [junit] java.lang.NoSuchMethodError: org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
    [junit] 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:121)
    [junit] 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:111)
    [junit] 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:268)
    [junit] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:241)
    [junit] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:254)
    [junit] 	at org.hibernate.engine.QueryParameters.<clinit>(QueryParameters.java:53)
    [junit] 	at java.lang.Class.forName0(Native Method)
    [junit] 	at java.lang.Class.forName(Class.java:169)
    [junit] 	at $Proxy12.<clinit>(Unknown Source)
    [junit] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    [junit] 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:588)
    [junit] 	at org.easymock.internal.JavaProxyFactory.createProxy(JavaProxyFactory.java:24)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:51)
    [junit] 	at org.easymock.MockControl.<init>(MockControl.java:44)
    [junit] 	at org.easymock.MockControl.createControl(MockControl.java:59)
    [junit] 	at org.springframework.orm.hibernate3.HibernateJtaTransactionTests.doTestJtaTransactionCommitWithPreBound(HibernateJtaTransactionTests.java:547)
    [junit] 	at org.springframework.orm.hibernate3.HibernateJtaTransactionTests.testJtaTransactionCommitWithPreBound(HibernateJtaTransactionTests.java:484)